// ****
// *
// * #defines for configuring the hydrostatic model
// *
// * (c) Dr. Stephen J. Bradshaw
// *
// * Source code generated by hydrad_tools on {{ date }}
// *
// ****

// **** Output ****
// **** End of Output ****

// **** Physics ****
#include "../../Radiation_Model/source/config.h"
{% if initial_conditions.isothermal -%}
#define ISOTHERMAL
{%- endif %}
{% if initial_conditions.use_poly_fit_gravity and general.poly_fit_gravity is defined -%}
#define USE_POLY_FIT_TO_GRAVITY
#define POLY_FIT_TO_GRAVITY_FILE "poly_fit.gravity"
{%- endif %}
{% if initial_conditions.use_poly_fit_magnetic_field and general.poly_fit_magnetic_field is defined -%}
#define USE_POLY_FIT_TO_MAGNETIC_FIELD
#define POLY_FIT_TO_MAGNETIC_FIELD_FILE "poly_fit.gravity"
{%- endif %}
{% if general.open_field -%}
#define OPEN_FIELD
{%- endif %}

// **** Solver ****
#define EPSILON {{ solver.epsilon | is_required }}

// **** Grid ****
{% if grid.adapt -%}#define ADAPT{%- endif %}
#define MIN_CELLS {{ minimum_cells | is_required }}
#define MAX_CELLS {{ maximum_cells | is_required }}
#define MAX_REFINEMENT_LEVEL {{ grid.maximum_refinement_level | is_required }}
#define MIN_DS {{ grid.minimum_delta_s | is_required | units_filter('cm') }}
#define MAX_VARIATION {{ grid.maximum_variation | is_required + 1.0}}
