// ****
// *
// * #defines for configuring the hydrostatic model
// *
// * (c) Dr. Stephen J. Bradshaw
// *
// * Source code generated by hydrad_tools on {{ date }}
// *
// ****

// **** Output ****
// **** End of Output ****

// **** Physics ****
#include "../../Radiation_Model/source/config.h"
{% if initial_conditions.isothermal -%}
#define ISOTHERMAL
{%- endif %}
{% if initial_conditions.use_tabulated_gravity -%}
#define USE_TABULATED_GRAVITY
#define TABULATED_GRAVITY_FILE {{ general.tabulated_gravity_file }}
{%- endif %}

// **** Solver ****
#define EPSILON {{ solver.epsilon }}

// **** Grid ****
{% if grid.adapt -%}#define ADAPT{%- endif %}
#define MIN_CELLS {{ grid.minimum_cells }}
#define MAX_CELLS {{ grid.maximum_cells }}
#define MAX_REFINEMENT_LEVEL {{ grid.maximum_refinement_level }}
#define MIN_DS {{ grid.minimum_delta_s | units_filter('cm') }}
#define MAX_VARIATION {{ grid.maximum_variation + 1.0}}
