[build-system]

requires = ["setuptools",
            "setuptools_scm",
            "wheel"]

build-backend = 'setuptools.build_meta'

[project.optional-dependencies]
docs =[
  "sphinx-automodapi",
  "sphinx-design",
  "sphinx-gallery",
  "sphinx",
  "sphinxcontrib-bibtex",
]
