// ****
// *
// * #defines for configuring the heating model
// *
// * (c) Dr. Stephen J. Bradshaw
// *
// * Source code generated by pydrad on {{ date }}
// *
// ****
#define ELECTRON_HEATING {{ heating.electron_heating | is_required }}
#define HYDROGEN_HEATING {{ 1.0 - heating.electron_heating }}
{% if heating.electron_heating == 1.0 %}#define ELECTRON_HEATING_ONLY{% endif %}
{% if heating.electron_heating == 0.0 %}#define HYDROGEN_HEATING_ONLY{% endif %}
{% if heating.beam %}#define BEAM_HEATING{% endif %}
{% if heating.alfven_wave %}#define ALFVEN_WAVE_HEATING{% endif %}
#include "../../Radiation_Model/source/config.h"
