// ****
// *
// * #defines for configuring the heating model
// *
// * (c) Dr. Stephen J. Bradshaw
// *
// * Source code generated by pydrad on {{ date }}
// *
// ****
#define HEATED_SPECIES {% if heating.heat_electrons -%}0{%- else -%}1{%- endif %}
{% if heating.beam %}#define BEAM_HEATING{% endif %}
{% if heating.alfven_wave %}#define ALFVEN_WAVE_HEATING{% endif %}
#include "../../Radiation_Model/source/config.h"
