# Only run this branch on pushes to master because the needed secret
# to clone HYDRAD is not available otherwise
name: Test with HYDRAD

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade codecov
        python -m pip install -r requirements/requirements-dev.txt
        python setup.py install
    - name: Clone HYDRAD
      uses: actions/checkout@v2
      with:
        repository: rice-solar-physics/HYDRAD
        token: ${{ secrets.PYDRAD_HYDRAD_CLONE }}
        path: HYDRAD
    - name: Test
      run: |
        pytest --hydrad-dir=$GITHUB_WORKSPACE/HYDRAD --cov=pydrad --cov-report=xml
    - name: Report coverage
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
        verbose: true
        file: ./coverage.xml
